#!/usr/bin/env bash
# list of commands that will Installing nginx on web-01

#update and install nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service
sudo service nginx start

#config the uncomplicated firewall (ufw) to allow incoming traffic for Nginx HTTP services
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#Creating an index.html page
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html


#testing Nginx config for syntax errors
sudo nginx -t

#Restarting Nginx
sudo service nginx restart
