#!/usr/bin/env bash
# configuring a new ubuntu machine to perform a 301-redirection

#make updates before installation
sudo apt-get update
#installing nginx
sudo apt-get -y install nginx

#Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

#Performing a 301-redirection
string_for_replacement="server_name_;\n\trewrite ^\/redirect_me https:\/\/github.com\/Amanda-Amata permanent;"
sudo sed -i "s/server_name_;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#Restarting Nginx services
sudo service nginx restart
