#!/usr/bin/env bash
#Configure HAproxy so that it send traffic to web-01 and web-02
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#HAproxy can be managed via an init script

#install HAproxy on a server
sudo apt-get update
sudo apt-get install software-properties-common -y
sudo apt-get update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
touch /etc/haproxy/haproxy.cfg

#configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo "
frontend amandabiotech.tech
	bind 0:80
	default_backend web_servers

backend web_servers
	balance roundrobin
        server 462740-web-01 54.160.75.184:80
        server 462740-web-02 54.160.66.133:80
" >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
