#!/usr/bin/env bash
#Configure HAproxy so that it send traffic to web-01 and web-02

#install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

#configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend amandabiotech.tech
	bind 0:80
	default_backend web_servers

backend web_servers
	balance roundrobin
        server 462740-web-01 54.160.75.184:80
        server 462740-web-02 54.160.66.133:80
' | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
